#### Stage dependencies
FROM ubuntu:latest

# Deal with Ubuntu's tzdata package stupidity
ENV DEBIAN_FRONTEND=noninteractive

# Install build dependencies
RUN apt-get update
RUN apt-get -y install wget gcc g++ gfortran make libblas-dev liblapack-dev libpcre3-dev libarpack2-dev \
  libcurl4-gnutls-dev libreadline-dev gnuplot-nox libhdf5-dev llvm-dev libqhull-dev \
  zlib1g-dev autoconf automake bison flex gperf gzip libtool perl rsync tar libsundials-dev \
  texinfo libqrupdate-dev
